// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechcareerBootcampFest4Project.Data.Concrete.EfCore;

#nullable disable

namespace TechcareerBootcampFest4Project.Migrations
{
    [DbContext(typeof(KiraSitesiContext))]
    partial class KiraSitesiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ArabaKategori", b =>
                {
                    b.Property<int>("ArabalarArabaID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KategorilerKategoriID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArabalarArabaID", "KategorilerKategoriID");

                    b.HasIndex("KategorilerKategoriID");

                    b.ToTable("ArabaKategori");
                });

            modelBuilder.Entity("TechcareerBootcampFest4Project.Entity.Araba", b =>
                {
                    b.Property<int>("ArabaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Başlık")
                        .HasColumnType("TEXT");

                    b.Property<string>("Görsel")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Kiralanabilir")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KiraÜcreti")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KoltukSayısı")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marka")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.HasKey("ArabaID");

                    b.ToTable("Arabalar");
                });

            modelBuilder.Entity("TechcareerBootcampFest4Project.Entity.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KategoriAdı")
                        .HasColumnType("INTEGER");

                    b.HasKey("KategoriID");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("TechcareerBootcampFest4Project.Entity.Kullanıcı", b =>
                {
                    b.Property<int>("KullanıcıID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ArabaID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Soyad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Şifre")
                        .HasColumnType("TEXT");

                    b.HasKey("KullanıcıID");

                    b.HasIndex("ArabaID")
                        .IsUnique();

                    b.ToTable("Kullanıcılar");
                });

            modelBuilder.Entity("ArabaKategori", b =>
                {
                    b.HasOne("TechcareerBootcampFest4Project.Entity.Araba", null)
                        .WithMany()
                        .HasForeignKey("ArabalarArabaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechcareerBootcampFest4Project.Entity.Kategori", null)
                        .WithMany()
                        .HasForeignKey("KategorilerKategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechcareerBootcampFest4Project.Entity.Kullanıcı", b =>
                {
                    b.HasOne("TechcareerBootcampFest4Project.Entity.Araba", "KiralananAraba")
                        .WithOne("KiralayanKullanıcı")
                        .HasForeignKey("TechcareerBootcampFest4Project.Entity.Kullanıcı", "ArabaID");

                    b.Navigation("KiralananAraba");
                });

            modelBuilder.Entity("TechcareerBootcampFest4Project.Entity.Araba", b =>
                {
                    b.Navigation("KiralayanKullanıcı");
                });
#pragma warning restore 612, 618
        }
    }
}
